export const FUNCTIONAL_GROUPS = [
  { id: 'motor', ko: '운동·안구운동', en: 'Movement & gaze' },
  { id: 'sensory', ko: '체성감각·청각', en: 'Sensation & hearing' },
  { id: 'visual', ko: '시각', en: 'Vision' },
  { id: 'language', ko: '언어', en: 'Language' },
  { id: 'cognition', ko: '주의·집행·정서', en: 'Attention, control & affect' },
  { id: 'memory', ko: '기억·공간', en: 'Memory & space' },
];

export const ATLAS_SOURCE = { title: 'Glasser et al. 2016 · HCP-MMP1.0', url: 'https://www.nature.com/articles/nature18933' };
export const ATLAS_SCOPE = '색으로 표시한 부분은 아래 HCP-MMP1.0 구획입니다. 집단 아틀라스의 경계이며 개인의 활성도·기능 경계를 측정한 결과는 아닙니다. 여러 구획을 묶은 항목은 관련 기능의 대표 범위를 보여줍니다.';
export const ATLAS_SCOPE_EN = 'Color marks the listed HCP-MMP1.0 parcels on a matching group-average surface, not measured activation or individual functional borders. Grouped parcels illustrate representative components of a wider functional system.';

function area(id, ko, en, short, group, parcels, view, location, locationEn, summary, summaryEn) {
  return { id, ko, en, short, group, parcels, view, location, locationEn, summary, summaryEn,
    labels: [], defaultSide: 'left', scope: ATLAS_SCOPE, scopeEn: ATLAS_SCOPE_EN, source: ATLAS_SOURCE };
}

export const ADDITIONAL_AREAS = [
  area('m1', '일차운동피질', 'Primary motor cortex', 'M1', 'motor', ['4'], 'lateral',
    '중심고랑 앞벽과 중심앞이랑, 안쪽면의 중심곁소엽 앞부분에 걸칩니다.',
    'Anterior bank of the central sulcus and precentral gyrus, extending into the anterior paracentral lobule medially.',
    '주로 반대쪽 신체의 자발적 움직임을 조절하며, 부위별 운동 표상이 배열되어 있습니다.',
    'Controls voluntary movement, predominantly of the opposite side of the body, with a somatotopic organization.'),
  area('fef', '전두안구영역', 'Frontal eye field', 'FEF', 'motor', ['FEF'], 'lateral',
    '전두엽의 위쪽 중심앞고랑 부근입니다.', 'Near the superior precentral sulcus in the frontal lobe.',
    '의도적인 신속안구운동과 시각적 주의 이동에 관여합니다.', 'Contributes to voluntary saccades and shifts of visual attention.'),
  area('s1', '일차체성감각피질', 'Primary somatosensory cortex', 'S1', 'sensory', ['3a', '3b', '1', '2'], 'lateral',
    '중심고랑의 바닥·뒤벽과 중심뒤이랑, 중심곁소엽 뒤부분에 걸칩니다.',
    'Fundus and posterior bank of the central sulcus, postcentral gyrus and posterior paracentral region.',
    '반대쪽 몸의 촉각과 고유감각 등을 처리합니다. 3a·3b·1·2의 기능과 연결은 서로 다릅니다.',
    'Processes touch and proprioception, mainly from the contralateral body. Areas 3a, 3b, 1 and 2 have distinct contributions.'),
  area('s2', '이차체성감각 관련 피질', 'Secondary somatosensory-related cortex', 'S2 / OP', 'sensory', ['OP1', 'OP4'], 'lateral',
    '가쪽고랑 안의 두정덮개에 위치한 OP1·OP4입니다.', 'OP1 and OP4 in the parietal operculum within the lateral fissure.',
    '촉각 정보를 통합하고 물체의 촉각적 식별과 감각 학습에 참여합니다.',
    'Integrates somatic information and contributes to tactile object discrimination and sensory learning.'),
  area('a1', '일차청각피질', 'Primary auditory cortex', 'A1', 'sensory', ['A1'], 'lateral',
    '측두엽 위면의 가로측두이랑 부근으로, 가쪽고랑 안에 묻혀 있습니다.',
    'On the superior temporal plane around the transverse temporal gyrus, buried inside the lateral fissure.',
    '소리의 주파수와 시간적 특징 등 초기 청각 정보를 처리합니다.',
    'Processes early auditory information including frequency and temporal features of sounds.'),
  area('auditory-belt', '청각 띠피질', 'Auditory belt cortex', 'Auditory belt', 'sensory', ['LBelt', 'MBelt', 'PBelt'], 'lateral',
    '측두엽 위면에서 일차청각피질 주변을 둘러싼 띠 구획입니다.',
    'Belt parcels surrounding primary auditory cortex on the superior temporal plane.',
    '복잡한 소리의 특징을 통합하며 청각 연합 처리에 참여합니다.',
    'Integrates complex acoustic features and contributes to auditory association processing.'),
  area('v1', '일차시각피질', 'Primary visual cortex', 'V1', 'visual', ['V1'], 'medial',
    '후두엽 안쪽면의 새발톱고랑 양쪽 벽을 따라 위치하며 후두극까지 이어집니다.',
    'Along the calcarine sulcus banks on the medial occipital surface, extending toward the occipital pole.',
    '반대쪽 시야의 초기 피질 처리를 담당하며 위치·방향·대비 등의 특징을 분석합니다.',
    'Performs early cortical processing of the contralateral visual field, including position, orientation and contrast.'),
  area('v2', '이차시각피질', 'Secondary visual cortex', 'V2', 'visual', ['V2'], 'medial',
    '안쪽 후두엽에서 V1을 위아래로 둘러싼 구획입니다.', 'Surrounds V1 dorsally and ventrally in medial occipital cortex.',
    '윤곽·형태·깊이 등 시각 특징의 통합에 참여합니다.', 'Integrates visual features including contours, form and depth.'),
  area('v3', '제3시각영역', 'Third visual area', 'V3', 'visual', ['V3'], 'medial',
    '후두엽에서 V2 바깥쪽의 등쪽·배쪽 시각 구획입니다.', 'Dorsal and ventral occipital visual territory outside V2.',
    '형태와 움직임을 포함한 시각 정보 처리에 참여합니다.', 'Contributes to visual processing of form and motion.'),
  area('v4', '제4시각영역', 'Fourth visual area', 'V4', 'visual', ['V4'], 'lateral',
    '후두엽의 바깥줄무늬피질에 위치한 HCP V4 구획입니다.', 'The HCP V4 parcel in extrastriate occipital cortex.',
    '색과 형태 등 시각 특징의 처리에 참여합니다. 색 지각은 이 구획에만 국한되지 않습니다.',
    'Contributes to color and form processing; color perception is not confined to this parcel.'),
  area('mt', '중간측두 시각영역', 'Middle temporal visual area', 'MT / V5', 'visual', ['MT', 'MST'], 'lateral',
    '가쪽 후두·측두 접합부의 MT와 인접 MST 구획입니다.', 'MT and neighboring MST at the lateral occipitotemporal junction.',
    '시각적 움직임, 이동 방향과 넓은 시야의 흐름을 분석합니다.', 'Processes visual motion, direction and wide-field optic flow.'),
  area('dlpfc', '등가쪽 전전두피질', 'Dorsolateral prefrontal cortex', 'DLPFC', 'cognition', ['46', '9-46d', 'p9-46v', 'a9-46v'], 'lateral',
    '가쪽 전두엽의 중간이마이랑 부근에서 46·9/46 관련 구획을 표시합니다.',
    'Area 46 and 9/46-related parcels around the middle frontal gyrus.',
    '작업기억, 규칙 유지와 목표에 따른 행동 조절에 참여합니다.',
    'Contributes to working memory, maintaining rules and goal-directed control.'),
  area('parietal-attention', '두정엽 주의 관련 피질', 'Parietal attention-related cortex', 'Parietal attention', 'cognition', ['LIPd', 'LIPv', 'IPS1'], 'lateral',
    '두정내고랑 부근의 LIPd·LIPv·IPS1 구획입니다.', 'LIPd, LIPv and IPS1 around the intraparietal sulcus.',
    '공간적 주의와 시각 정보에 따른 안구·도달 운동 계획에 관여합니다.',
    'Contributes to spatial attention and visually guided gaze and action planning.'),
  area('acc', '앞대상피질', 'Anterior cingulate cortex', 'ACC', 'cognition', ['a24', 'p24', 'a32pr', 'p32pr'], 'medial',
    '뇌량 앞부분 위의 안쪽 전두엽에 위치한 앞대상 관련 구획입니다.',
    'Anterior cingulate-related parcels on the medial frontal surface above the anterior corpus callosum.',
    '행동 결과·갈등의 감시, 동기와 정서·자율신경 반응 조절에 참여합니다.',
    'Contributes to monitoring outcomes and conflict, motivation, and regulation of affective and autonomic responses.'),
  area('anterior-insula', '앞뇌섬엽', 'Anterior insular cortex', 'Anterior insula', 'cognition', ['AVI', 'AAIC'], 'lateral',
    '가쪽고랑 깊은 곳의 앞쪽 뇌섬엽입니다. 주변 덮개를 투명하게 하여 확인할 수 있습니다.',
    'Anterior insula deep within the lateral fissure, visible through transparent opercular context.',
    '몸 내부 상태의 인식, 정서와 중요한 자극에 대한 주의 전환에 관여합니다.',
    'Contributes to interoception, affect and reorienting attention to salient events.'),
  area('entorhinal', '내후각피질', 'Entorhinal cortex', 'Entorhinal', 'memory', ['EC'], 'medial',
    '안쪽 측두엽의 앞쪽 해마곁이랑 부근입니다.', 'In the anterior parahippocampal region of the medial temporal lobe.',
    '해마와 대뇌피질 사이의 정보 교환, 기억과 공간 표상에 참여합니다.',
    'Links hippocampal and neocortical processing and contributes to memory and spatial representations.'),
  area('retrosplenial', '뇌량팽대뒤피질', 'Retrosplenial cortex', 'Retrosplenial', 'memory', ['RSC'], 'medial',
    '대뇌 안쪽면의 뇌량팽대 뒤쪽 부근입니다.', 'On the medial surface behind the splenium of the corpus callosum.',
    '장소·맥락 기억과 공간 방향 찾기에 참여합니다.', 'Contributes to contextual memory and spatial orientation.'),
];
