import { ADDITIONAL_AREAS } from './functional-catalog.js';
export { FUNCTIONAL_GROUPS } from './functional-catalog.js';

const establishedAreas = [
  { id: "sma",
    ko: "보완운동영역",
    en: "Supplementary motor area, SMA",
    short: "SMA",
    aliases: "보조운동영역 supplemental motor",
    defaultSide: "left",
    view: "medial",
    labels: [],
    location: "대뇌 안쪽면의 뒤쪽 위이마이랑 부근, 일차운동피질의 다리 영역 앞쪽에 위치합니다.",
    locationEn: "On the medial posterior superior frontal region, anterior to the leg representation of primary motor cortex.",
    summary: "스스로 시작하는 동작의 준비, 동작 순서 구성과 양손 움직임의 조율에 관여합니다.",
    summaryEn: "Contributes to preparation of self-initiated actions, movement sequences and coordination between the hands.",
    scope: "색으로 표시한 부분은 아래 HCP-MMP1.0 구획입니다. 집단 아틀라스의 경계이며 개인의 활성도·기능 경계를 측정한 결과는 아닙니다. 여러 구획을 묶은 항목은 관련 기능의 대표 범위를 보여줍니다. 6ma·6mp는 SMA의 대표 구획이며 SMA/pre-SMA의 구분과 완전히 동일한 경계로 정의하지 않습니다.",
    scopeEn: "Color marks the listed HCP-MMP1.0 parcels on a matching group-average surface, not measured activation or individual functional borders. Grouped parcels illustrate representative components of a wider functional system. Areas 6ma/6mp illustrate SMA components, not exact equivalence to the SMA/pre-SMA division.",
    source: {"title":"Glasser et al. 2016 · HCP-MMP1.0","url":"https://www.nature.com/articles/nature18933"},
    group: "motor",
    parcels: ["6ma","6mp"] },
  { id: "premotor",
    ko: "전운동피질",
    en: "Premotor cortex",
    short: "Premotor",
    aliases: "운동앞피질 premotor PMC",
    defaultSide: "left",
    view: "lateral",
    labels: [],
    location: "가쪽 전두엽에서 일차운동피질 앞쪽에 위치하며, 등쪽과 배쪽 전운동 영역으로 나눕니다.",
    locationEn: "In the lateral frontal lobe anterior to primary motor cortex, with dorsal and ventral premotor regions.",
    summary: "감각 단서에 맞는 동작을 선택하고 준비하며, 목표를 향한 팔·손 움직임 등을 계획하는 데 관여합니다.",
    summaryEn: "Helps select and prepare movements using sensory cues, including planning goal-directed arm and hand actions.",
    scope: "색으로 표시한 부분은 아래 HCP-MMP1.0 구획입니다. 집단 아틀라스의 경계이며 개인의 활성도·기능 경계를 측정한 결과는 아닙니다. 여러 구획을 묶은 항목은 관련 기능의 대표 범위를 보여줍니다.",
    scopeEn: "Color marks the listed HCP-MMP1.0 parcels on a matching group-average surface, not measured activation or individual functional borders. Grouped parcels illustrate representative components of a wider functional system.",
    source: {"title":"Glasser et al. 2016 · HCP-MMP1.0","url":"https://www.nature.com/articles/nature18933"},
    group: "motor",
    parcels: ["6a","6d","6v","6r"] },
  { id: "broca",
    ko: "브로카 영역",
    en: "Broca's area",
    short: "Broca",
    aliases: "브로카 언어 산출 BA44 BA45",
    defaultSide: "left",
    view: "lateral",
    labels: [],
    location: "언어 우세 반구의 아래이마이랑 덮개부분과 삼각부분이 대표적인 해부학적 위치입니다. 보통 좌측을 예시로 사용합니다.",
    locationEn: "Classically associated with pars opercularis and pars triangularis of the inferior frontal gyrus in the language-dominant hemisphere, usually illustrated on the left.",
    summary: "말과 문장을 구성하고 발화를 계획하는 언어 연결망에 참여합니다. 언어 산출은 이 영역만의 기능이 아닙니다.",
    summaryEn: "Participates in networks for speech planning and the construction of language. Speech production depends on a wider network.",
    scope: "색으로 표시한 부분은 아래 HCP-MMP1.0 구획입니다. 집단 아틀라스의 경계이며 개인의 활성도·기능 경계를 측정한 결과는 아닙니다. 여러 구획을 묶은 항목은 관련 기능의 대표 범위를 보여줍니다. 우측은 대응 구획이며 개인의 언어 우세 반구를 판정한 결과가 아닙니다.",
    scopeEn: "Color marks the listed HCP-MMP1.0 parcels on a matching group-average surface, not measured activation or individual functional borders. Grouped parcels illustrate representative components of a wider functional system. Right-sided parcels are homologues, not a determination of individual language dominance.",
    source: {"title":"Glasser et al. 2016 · HCP-MMP1.0","url":"https://www.nature.com/articles/nature18933"},
    group: "language",
    parcels: ["44","45"] },
  { id: "wernicke",
    ko: "베르니케 관련 뒤쪽 언어영역",
    en: "Wernicke-related posterior language regions",
    short: "Wernicke",
    aliases: "베르니케 언어 이해 BA22",
    defaultSide: "left",
    view: "lateral",
    labels: [],
    location: "뒤쪽 가쪽고랑 주변의 PSL과 뒤쪽 위측두 영역의 STV를 표시합니다.",
    locationEn: "PSL around the posterior lateral fissure and STV in the posterior superior temporal region.",
    summary: "말소리를 언어 정보와 연결하는 과정에 관여하며, 단어와 문장의 이해는 분산된 언어 연결망을 통해 이루어집니다.",
    summaryEn: "Contributes to relating speech sounds to linguistic information; word and sentence comprehension depend on distributed language networks.",
    scope: "색으로 표시한 부분은 아래 HCP-MMP1.0 구획입니다. 집단 아틀라스의 경계이며 개인의 활성도·기능 경계를 측정한 결과는 아닙니다. 여러 구획을 묶은 항목은 관련 기능의 대표 범위를 보여줍니다. 베르니케 영역에는 합의된 단일 경계가 없습니다. PSL·STV는 대표 구획이며 전체 베르니케 영역이나 전체 언어 이해 연결망과 동일하지 않습니다.",
    scopeEn: "Color marks the listed HCP-MMP1.0 parcels on a matching group-average surface, not measured activation or individual functional borders. Grouped parcels illustrate representative components of a wider functional system. Wernicke’s area has no universally agreed boundary. PSL/STV are illustrative components, not the entire Wernicke area or comprehension network.",
    source: {"title":"Glasser et al. 2016 · HCP-MMP1.0","url":"https://www.nature.com/articles/nature18933"},
    group: "language",
    parcels: ["PSL","STV"] },
  { id: "hippocampus",
    ko: "해마",
    en: "Hippocampus",
    short: "Hippocampus",
    aliases: "기억 hippocampus 해마",
    defaultSide: "both",
    view: "oblique",
    labels: ["Hippocampus"],
    location: "양쪽 안쪽 측두엽 깊은 곳에 위치합니다. 주변 피질을 투명하게 하여 내부의 해마를 표시합니다.",
    locationEn: "Deep within the medial temporal lobe on each side. The surrounding cortex is made transparent to reveal the hippocampi.",
    summary: "새로운 일화·서술 기억의 형성과 공간 탐색에 관여합니다. 기억이 저장되는 유일한 부위는 아닙니다.",
    summaryEn: "Contributes to formation of new episodic/declarative memories and spatial navigation. It is not the sole site of memory storage.",
    scope: "해마 전체의 해부 형상입니다. CA1–CA4, 치아이랑, 해마이행부의 세부 구획이나 기능 활성도를 분할한 자료는 아닙니다.",
    scopeEn: "These are whole anatomical hippocampal meshes, not delineated CA1–CA4, dentate gyrus or subicular fields, nor functional activation maps.",
    source: {"title":"Neuroscience · The limbic system","url":"https://www.ncbi.nlm.nih.gov/books/NBK11060/"},
    group: "memory",
    parcels: [] }
];

export const FUNCTIONAL_AREAS = [...ADDITIONAL_AREAS, ...establishedAreas];

export function functionalParts(parts, area, hemisphere) {
  return parts.filter(p => area.labels.includes(p.label) && (hemisphere === 'both' || p.side === hemisphere));
}
